// GENERATED from DocWen Machine Protocol v1 conformance fixtures; consumer-specific input IDs are normalized here.
export const EXACT_TWO_MARKDOWN_TO_DOCX_CAPABILITY = {
  capability_id: "convert.markdown.to_docx",
  operation: "convert",
  input_shape: {
    slots: [
      {
        role: "neutral_document",
        kind: "document",
        media_types: ["application/vnd.docwen.resolved-document+json"],
        min_items: 1,
        max_items: 1,
      },
      {
        role: "numbering_export_plan",
        kind: "resource",
        media_types: ["application/vnd.docwen.numbering-export-plan+json"],
        min_items: 1,
        max_items: 1,
      },
    ],
    undeclared_roles: "reject",
  },
  output_media_types: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
  output_shape: {
    cardinality: "one",
    artifact_kinds: ["document"],
    relation_types: [],
    atomic_bundle: true,
  },
  options_schema: {},
  availability: "available",
  dependencies: [],
  limitations: [
    {
      severity: "warning",
      code: "resolved_document.provider_owned_semantics",
      message:
        "DocWen consumes already-resolved targets, citations, resources, and numbering facts; it does not infer them from authored text.",
    },
  ],
};

export const NEUTRAL_DOCUMENT = {
  $schema: "urn:docwen:schema:resolved-document:v1",
  schema: "docwen.resolved_document.v1",
  input_id: "docwen-neutral-1d28a20836a07c7818a289b51a7ef4ca",
  source_sha256: "1d28a20836a07c7818a289b51a7ef4ca2b1dc8d731175e02b831750dc27ab962",
  plan_sha256: "2aecfd6cfa60bf788eecae7fbb7494642fff79af5988969ad34926f0e2425054",
  document: {
    authored_markdown:
      "# Architecture ^h-7f3a\n\nFigure: System overview ^system-overview\n\n![[system.png]]\n\nTable: Results ^results-main\n\n| Metric | Value |\n|---|---|\n| Score | 95 |\n\nEquation: ^energy-main\n\n$$\nE = mc^2\n$$\n\nCode: Entry point ^entry-main\n\n```rust\nfn main() {}\n```\n\nStable: @[[#^h-7f3a]] and @[[#^system-overview|System overview]].\nOrdinary: [[#^system-overview]] and ![[Guide#^h-7f3a]].\nCitation: @cite-one.\n",
    targets: [
      {
        source_start: 0,
        source_end: 22,
        source_slice_sha256: "9db146b8c77e8ad9379cfb192290d6668281b24e680e3228786989beca20265a",
        kind: "heading",
        target_id: "h-7f3a",
        heading_level: 1,
        authored_text: "Architecture",
      },
      {
        source_start: 24,
        source_end: 64,
        source_slice_sha256: "1277fbdf915dde6cda3ab80a506db9d8ec8a077d9bec04646748fb7369d1f033",
        kind: "figure",
        target_id: "system-overview",
        heading_level: null,
        authored_text: "System overview",
      },
      {
        source_start: 83,
        source_end: 111,
        source_slice_sha256: "82c070f6467923aa51bc75b9fa5aed5eb7f99232b19b099657a9aa2f9737fcc1",
        kind: "table",
        target_id: "results-main",
        heading_level: null,
        authored_text: "Results",
      },
      {
        source_start: 158,
        source_end: 180,
        source_slice_sha256: "52484aa20fbf4788aebc2f7343dd7b4b375711b4b720210b0e6ca802cc07297a",
        kind: "equation",
        target_id: "energy-main",
        heading_level: null,
        authored_text: "",
      },
      {
        source_start: 198,
        source_end: 227,
        source_slice_sha256: "2a756b8a621ec190b9eea85a367a410eb5cd0654a301c31d50f999490a87694a",
        kind: "code_block",
        target_id: "entry-main",
        heading_level: null,
        authored_text: "Entry point",
      },
    ],
    references: [
      {
        source_start: 263,
        source_end: 276,
        source_slice_sha256: "850ccceb2327d91136ce996a3577d080a287988504857907e32f679a3819959c",
        authored_token: "@[[#^h-7f3a]]",
        target_source_start: 0,
        target_source_end: 22,
        target_kind: "heading",
        target_id: "h-7f3a",
        cached_number: "1",
        alias: null,
      },
      {
        source_start: 281,
        source_end: 319,
        source_slice_sha256: "391f374d10a10a9deb0bf5306378e6a55e271355a3a9b8128394c1bd947976ee",
        authored_token: "@[[#^system-overview|System overview]]",
        target_source_start: 24,
        target_source_end: 64,
        target_kind: "figure",
        target_id: "system-overview",
        cached_number: "1",
        alias: "System overview",
      },
    ],
    resource_occurrences: [
      {
        source_start: 66,
        source_end: 81,
        source_slice_sha256: "b3709c74910dd4adde5211af6f88b605c25f36a2e74817fead91a52462e9bf4d",
        authored_token: "![[system.png]]",
        authored_locator: "system.png",
        resource_id: "image-system",
      },
    ],
    citations: [
      {
        source_start: 387,
        source_end: 396,
        source_slice_sha256: "5f6357be6410398a73822925e446d175effed3cdab0d5d5ad38e28ad262eae28",
        authored_token: "@cite-one",
        form: "narrative",
        cluster_id: "citation-one",
        items: [
          {
            citation_key: "cite-one",
            record_id: "ref-one",
            record_sha256: "b457bbe0bf6e46d3a84c2e7b02afee45d211e6567e53658c2b37d343013a6df7",
            presentation: "One (2026)",
          },
        ],
        cached_result: "One (2026)",
      },
    ],
    resources: [
      {
        resource_id: "bibliography-main",
        role: "bibliography",
        media_type: "application/vnd.docwen.semantic-bibliography+json",
        size_bytes: 177,
        sha256: "27bfb40d2fb8044bcf7b5608645da0a95296e1f03920b5317c3967e7adfe0a6c",
        content_base64:
          "eyJzY2hlbWEiOiJkb2N3ZW4uc2VtYW50aWNfYmlibGlvZ3JhcGh5LnYxIiwiZW50cmllcyI6W3siaXRlbV9pZCI6InJlZi1vbmUiLCJydW5zIjpbeyJ0ZXh0IjoiT25lLCBBLiAoMjAyNikuIEV4YWN0IHR3by4iLCJpdGFsaWMiOnRydWUsImhyZWYiOiJodHRwczovL2V4YW1wbGUudGVzdC9yZWYtb25lIn1dfV19",
      },
      {
        resource_id: "image-system",
        role: "linked_resource",
        media_type: "image/png",
        size_bytes: 75,
        sha256: "76f04b5505024667600de38630b5595fcbbf7449ccd5ab89baaeb9b4b08f4434",
        content_base64:
          "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAEklEQVR4nGNUSFjAwMDAxAAGAA0qASTlOPBgAAAAAElFTkSuQmCC",
      },
    ],
  },
};

export const NUMBERING_PLAN = {
  $schema: "urn:docwen:schema:numbering-export-plan:v1",
  schema: "docwen.numbering_export_plan.v1",
  input_id: "docwen-neutral-1d28a20836a07c7818a289b51a7ef4ca",
  source_sha256: "1d28a20836a07c7818a289b51a7ef4ca2b1dc8d731175e02b831750dc27ab962",
  plan_sha256: "2aecfd6cfa60bf788eecae7fbb7494642fff79af5988969ad34926f0e2425054",
  plan: {
    heading_definitions: [
      {
        definition_id: "heading-default",
        levels: [
          {
            display: [
              {
                counter: {
                  level: 1,
                  number_format: "arabic_half",
                },
              },
            ],
            level: 1,
            number_format: "arabic_half",
            restart_after_level: null,
            start: 1,
            suffix: "space",
          },
        ],
      },
    ],
    heading_instances: [
      {
        definition_id: "heading-default",
        instance_id: "heading-instance-1",
        starts: [],
      },
    ],
    targets: [
      {
        derived_number: "1",
        enabled: true,
        kind: "heading",
        materialization: {
          definition_id: "heading-default",
          instance_id: "heading-instance-1",
          level: 1,
          type: "heading_list",
        },
        source_end: 22,
        source_start: 0,
        target_id: "h-7f3a",
      },
      {
        derived_number: "1",
        enabled: true,
        kind: "figure",
        materialization: {
          chapter_cached_number: null,
          chapter_heading_level: null,
          chapter_heading_style: null,
          chapter_separator: null,
          counter: "Figure",
          label_separator: " ",
          localized_label: "Figure",
          number_format: "arabic_half",
          restart_heading_level: null,
          restart_heading_style: null,
          sequence_action: "continue",
          sequence_cached_number: "1",
          start_value: null,
          type: "simple_seq",
        },
        source_end: 64,
        source_start: 24,
        target_id: "system-overview",
      },
      {
        derived_number: "1",
        enabled: true,
        kind: "table",
        materialization: {
          chapter_cached_number: null,
          chapter_heading_level: null,
          chapter_heading_style: null,
          chapter_separator: null,
          counter: "Table",
          label_separator: " ",
          localized_label: "Table",
          number_format: "arabic_half",
          restart_heading_level: null,
          restart_heading_style: null,
          sequence_action: "continue",
          sequence_cached_number: "1",
          start_value: null,
          type: "simple_seq",
        },
        source_end: 111,
        source_start: 83,
        target_id: "results-main",
      },
      {
        derived_number: "1",
        enabled: true,
        kind: "equation",
        materialization: {
          chapter_cached_number: null,
          chapter_heading_level: null,
          chapter_heading_style: null,
          chapter_separator: null,
          counter: "Equation",
          label_separator: " ",
          localized_label: "Equation",
          number_format: "arabic_half",
          restart_heading_level: null,
          restart_heading_style: null,
          sequence_action: "continue",
          sequence_cached_number: "1",
          start_value: null,
          type: "simple_seq",
        },
        source_end: 180,
        source_start: 158,
        target_id: "energy-main",
      },
      {
        derived_number: "1",
        enabled: true,
        kind: "code_block",
        materialization: {
          chapter_cached_number: null,
          chapter_heading_level: null,
          chapter_heading_style: null,
          chapter_separator: null,
          counter: "Code",
          label_separator: " ",
          localized_label: "Code",
          number_format: "arabic_half",
          restart_heading_level: null,
          restart_heading_style: null,
          sequence_action: "continue",
          sequence_cached_number: "1",
          start_value: null,
          type: "simple_seq",
        },
        source_end: 227,
        source_start: 198,
        target_id: "entry-main",
      },
    ],
  },
};
